# Generated by Django 4.1 on 2022-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
