# Generated by Django 4.1 on 2022-09-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_stream_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
