# Generated by Django 4.1 on 2022-10-05 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commenter',
        ),
    ]
