# Generated by Django 4.1 on 2022-10-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='lives_in',
        ),
    ]
